const products=[
 {id:1,name:'Резец дорожной фрезы',article:'AG-RF-018',oem:'OEM: по запросу',type:'road',category:'cutting',model:['milling'],image:0,desc:'Для рабочих барабанов дорожно-фрезерной техники.'},
 {id:2,name:'Цепь конвейерная',article:'AG-CV-240',oem:'OEM: по запросу',type:'road',category:'conveyor',model:['milling','paver'],image:1,desc:'Элемент конвейерной системы дорожной техники.'},
 {id:3,name:'Каток опорный',article:'AG-UR-310',oem:'OEM: по запросу',type:'construction',category:'undercarriage',model:['excavator'],image:2,desc:'Элемент ходовой части гусеничной техники.'},
 {id:4,name:'Звезда приводная',article:'AG-SP-440',oem:'OEM: по запросу',type:'construction',category:'undercarriage',model:['excavator'],image:3,desc:'Компонент привода гусеничной ходовой системы.'},
 {id:5,name:'Фильтр гидравлический',article:'AG-HF-152',oem:'OEM: по запросу',type:'road',category:'service',model:['milling','paver','roller'],image:4,desc:'Фильтрующий элемент гидравлической системы.'},
 {id:6,name:'Подшипниковый узел',article:'AG-BR-620',oem:'OEM: по запросу',type:'road',category:'conveyor',model:['milling','paver'],image:5,desc:'Узел для вращающихся механизмов оборудования.'},
 {id:7,name:'Ролик конвейера',article:'AG-CR-280',oem:'OEM: по запросу',type:'road',category:'conveyor',model:['milling','paver'],image:6,desc:'Опорный ролик конвейерной системы.'},
 {id:8,name:'Плита износостойкая',article:'AG-WP-510',oem:'OEM: по запросу',type:'construction',category:'cutting',model:['excavator'],image:7,desc:'Защитная деталь для нагруженных рабочих узлов.'},
 {id:9,name:'Гидромотор',article:'AG-HM-730',oem:'OEM: по запросу',type:'construction',category:'hydraulics',model:['excavator'],image:8,desc:'Компонент гидравлического привода спецтехники.'}
];
const labels={road:'Дорожно-строительная',construction:'Строительная',cutting:'Режущий инструмент',undercarriage:'Ходовая часть',conveyor:'Конвейерная система',hydraulics:'Гидравлика',service:'Фильтры и обслуживание',milling:'Дорожная фреза',paver:'Асфальтоукладчик',roller:'Каток',excavator:'Экскаватор'};
const state={query:'',filters:{type:new Set(),category:new Set(),model:new Set()},sort:'recommended',view:'grid',list:new Set()};
const params=new URLSearchParams(location.search);state.query=params.get('q')||'';if(params.get('type'))state.filters.type.add(params.get('type'));
const grid=document.querySelector('#product-grid'),active=document.querySelector('#active-filters'),count=document.querySelector('#result-count'),pageTitle=document.querySelector('#page-title'),pageDescription=document.querySelector('#page-description'),searchInput=document.querySelector('#catalog-search');searchInput.value=state.query;
const pos=i=>`${(i%3)*50}% ${Math.floor(i/3)*50}%`;

function filtered(){let list=products.filter(p=>{const hay=(p.name+' '+p.article+' '+p.desc).toLowerCase();if(state.query&&!hay.includes(state.query.toLowerCase()))return false;for(const key of ['type','category'])if(state.filters[key].size&&!state.filters[key].has(p[key]))return false;if(state.filters.model.size&&![...state.filters.model].some(v=>p.model.includes(v)))return false;return true});if(state.sort==='name')list.sort((a,b)=>a.name.localeCompare(b.name,'ru'));if(state.sort==='article')list.sort((a,b)=>a.article.localeCompare(b.article));return list}
function setHeading(){if(state.query){pageTitle.textContent='РЕЗУЛЬТАТЫ ПОИСКА';pageDescription.textContent=`По запросу «${state.query}»`;}else if(state.filters.type.size===1){const type=[...state.filters.type][0];pageTitle.textContent=type==='road'?'ДОРОЖНО-СТРОИТЕЛЬНАЯ ТЕХНИКА':'СТРОИТЕЛЬНАЯ ТЕХНИКА';pageDescription.textContent='Каталог запчастей SCP-AGGA по выбранному типу техники.';}else{pageTitle.textContent='ВСЕ ЗАПЧАСТИ';pageDescription.textContent='Подберите необходимые позиции по типу техники, категории или артикулу.'}}
function render(){const list=filtered();count.textContent=list.length;grid.classList.toggle('list-view',state.view==='list');grid.innerHTML=list.map(p=>`<article class="product-card"><div class="product-image" style="background-position:${pos(p.image)}"></div><div class="product-card-body"><div class="product-meta"><span>АРТИКУЛ: ${p.article}</span><span>${p.oem}</span></div><h3>${p.name}</h3><p>${p.desc}</p><button class="card-action ${state.list.has(p.id)?'added':''}" type="button" data-add="${p.id}"><span>${state.list.has(p.id)?'ДОБАВЛЕНО В СПИСОК':'ДОБАВИТЬ В СПИСОК'}</span><b>${state.list.has(p.id)?'✓':'+'}</b></button></div></article>`).join('');document.querySelector('#empty-state').classList.toggle('hidden',list.length>0);renderChips();setHeading();updateCounts()}
function renderChips(){const chips=[];if(state.query)chips.push(`<button class="filter-chip" data-query>Поиск: ${state.query}<b>×</b></button>`);Object.entries(state.filters).forEach(([key,set])=>set.forEach(value=>chips.push(`<button class="filter-chip" data-filter="${key}:${value}">${labels[value]}<b>×</b></button>`)));active.innerHTML=chips.join('');const n=chips.length;document.querySelector('#mobile-filter-count').textContent=n||'';document.querySelector('#mobile-filter-count').style.display=n?'inline':'none'}
function updateCounts(){const n=state.list.size;document.querySelector('#header-count').textContent=n}
function syncChecks(){document.querySelectorAll('.filters input').forEach(input=>input.checked=state.filters[input.name].has(input.value))}
function reset(){state.query='';Object.values(state.filters).forEach(set=>set.clear());searchInput.value='';history.replaceState({},'',location.pathname);syncChecks();render()}
document.querySelectorAll('.filters input').forEach(input=>input.addEventListener('change',()=>{input.checked?state.filters[input.name].add(input.value):state.filters[input.name].delete(input.value);render()}));syncChecks();
grid.addEventListener('click',e=>{const button=e.target.closest('[data-add]');if(!button)return;const id=Number(button.dataset.add);state.list.has(id)?state.list.delete(id):state.list.add(id);render()});
active.addEventListener('click',e=>{const button=e.target.closest('button');if(!button)return;if(button.dataset.query!==undefined){state.query='';searchInput.value=''}else{const [key,value]=button.dataset.filter.split(':');state.filters[key].delete(value);syncChecks()}render()});
document.querySelector('#sort').addEventListener('change',e=>{state.sort=e.target.value;render()});document.querySelectorAll('.view-button').forEach(button=>button.addEventListener('click',()=>{state.view=button.dataset.view;document.querySelectorAll('.view-button').forEach(b=>b.classList.toggle('active',b===button));render()}));
document.querySelector('#catalog-search-form').addEventListener('submit',e=>{e.preventDefault();state.query=searchInput.value.trim();history.replaceState({},'',state.query?'?q='+encodeURIComponent(state.query):location.pathname);render()});
document.querySelector('#reset-filters').addEventListener('click',reset);document.querySelector('#empty-reset').addEventListener('click',reset);
const filters=document.querySelector('#filters');document.querySelector('.filter-open').addEventListener('click',()=>filters.classList.add('open'));document.querySelector('.filters-close').addEventListener('click',()=>filters.classList.remove('open'));document.querySelector('.apply-mobile').addEventListener('click',()=>filters.classList.remove('open'));
const drawer=document.querySelector('#request-drawer'),drawerItems=document.querySelector('#drawer-items'),drawerForm=document.querySelector('#request-form');
function openDrawer(forceForm=false){drawer.classList.remove('hidden');document.body.style.overflow='hidden';drawer.querySelector('.drawer-success').classList.add('hidden');drawerForm.classList.remove('hidden');drawerItems.classList.remove('hidden');document.querySelector('#drawer-title').textContent=state.list.size?'ВАШ СПИСОК':'ПОЛУЧИТЬ ПРЕДЛОЖЕНИЕ';drawerItems.innerHTML=state.list.size?[...state.list].map(id=>{const p=products.find(x=>x.id===id);return `<div class="drawer-product"><i style="background-position:${pos(p.image)}"></i><div><b>${p.name}</b><span>${p.article}</span></div><button data-remove="${p.id}">×</button></div>`}).join(''):'<p>Добавьте позиции из каталога или отправьте готовый перечень менеджеру.</p>'}
function closeDrawer(){drawer.classList.add('hidden');document.body.style.overflow=''}
['#open-list','#header-request','#mobile-request','#filter-request','#catalog-request','.footer-request','#footer-list'].forEach(sel=>document.querySelector(sel)?.addEventListener('click',openDrawer));document.querySelector('.drawer-close').addEventListener('click',closeDrawer);document.querySelector('.drawer-shade').addEventListener('click',closeDrawer);drawerItems.addEventListener('click',e=>{const b=e.target.closest('[data-remove]');if(!b)return;state.list.delete(Number(b.dataset.remove));openDrawer();render()});drawerForm.addEventListener('submit',e=>{e.preventDefault();drawerForm.classList.add('hidden');drawerItems.classList.add('hidden');drawer.querySelector('.drawer-success').classList.remove('hidden')});
document.querySelector('.menu-toggle').addEventListener('click',()=>document.querySelector('.mobile-menu').classList.add('open'));document.querySelector('.mobile-menu-head button').addEventListener('click',()=>document.querySelector('.mobile-menu').classList.remove('open'));
render();
